include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    avoid_single_cascade_in_expression_statements: ignore
    implementation_imports: ignore
    leading_newlines_in_multiline_strings: ignore
    avoid_classes_with_only_static_members: ignore
    directives_ordering: ignore
    # on/off
    require_trailing_commas: ignore
    depend_on_referenced_packages: ignore