name: sw_vehicles_pro
description: The teacher version of a demo app for learning proposes
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  injectable: ^1.5.0
  recase: ^4.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.2
  freezed: ^1.1.0
  lint: ^1.8.1
  build_runner: ^2.1.7
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#1c1e22"
  image: assets/images/vehicle-icon-small.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/vehicle-icon-extra-large.png"
  image_path_android: "assets/images/vehicle-icon-extra-large.png"
  adaptive_icon_background: "assets/images/vehicle-icon-bg.png"
  adaptive_icon_foreground: "assets/images/vehicle-icon-large.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Death Star
      fonts:
        - asset: assets/fonts/death-star.ttf
